### ISSUE TITLE
Improvements tracker

### ISSUE THREAD

**Issue by marianagyby** [UBC-MDS/dragracerviz#52]
Modification: Add reset button to return filters to default settings
Source: Peer review milestone 3 [backend comment](https://github.ubc.ca/fdandrea/532-peer-review/issues/6#issuecomment-23066)
Team member: Marian Agyby (@marianagyby)
Commit/s: [commit link](https://github.com/UBC-MDS/dragracerviz/commit/b7d2731d7033a3199bf48514e19518dbb1150680)

**Comment by carolinetang77** [comment]
Modification: Improvement - Making the season filter optional instead of mandatory, and allowing selecting multiple seasons
Source: Group discussion + [Peer review backend comment](https://github.ubc.ca/fdandrea/532-peer-review/issues/6#issuecomment-23066)
Team member: Caroline Tang (@carolinetang77)
Commit: https://github.com/UBC-MDS/dragracerviz/commit/193672b3c74024342c0225816f95251b025dff15

Modification: Other category filters work as a union instead of intersection (i.e. selecting finalists and miss congeniality gives both groups instead of only queens who were both)
Source: [Peer review frontend comment](https://github.ubc.ca/fdandrea/532-peer-review/issues/6#issuecomment-23006)
Team member: Caroline Tang (@carolinetang77)
Commit: https://github.com/UBC-MDS/dragracerviz/commit/b8c139ec1b16650b138d3c9ac8de39fce53c9753

Modification: Improvement - Adding visible remove buttons to options for seasons and queens
Note: Options could be removed with the backspace button but it wasn't possible to do so by clicking the option itself
Source: [Peer review backend comment](https://github.ubc.ca/fdandrea/532-peer-review/issues/6#issuecomment-23066) + [Milestone 2 feedback](https://github.com/UBC-MDS/dragracerviz/issues/47)
Team member: Caroline Tang (@carolinetang77)
Commit: https://github.com/UBC-MDS/dragracerviz/commit/c5e7697558ddcb1621feb430dbbabfbbd8676bf2

**Comment by shaunhutch** [comment]
Modification: Improvement -  Adding default zoom on the map, so if one queen is selected, the map doesn't zoom into the street view of the map.
Source: Group Discussion
Team member: Shaun Hutchinson @shaunhutch 
Commit: [68f70da](https://github.com/UBC-MDS/dragracerviz/pull/53/commits/68f70daeedff99f04d08c1972ea80522b3119779)

Modification: Improvement -  Adding cluster options so that markers do not stack on top of each other.
Source: Group Discussion
Team member: Shaun Hutchinson @shaunhutch 
Commit: [1100a47](https://github.com/UBC-MDS/dragracerviz/pull/53/commits/1100a475349a6e1b75e7981cdfd9114ff1cce002)

Modification: Improvement -  Adding marker icons of RuPaul for the leaflet map.
Source: Florencia's Suggestion
Team member: Shaun Hutchinson @shaunhutch 
Commit: [d4a5fbf](https://github.com/UBC-MDS/dragracerviz/pull/53/commits/d4a5fbf8d0de97340a96feef367e409e3abe0ae6)

**Comment by dhruvinishar** [comment]
Modification: Improvement - Adjusted the Age slider to restrict values to the filtered data and not the entire range of age values for the data
Source: Group Discussion
Team member: Dhruvi Nishar @dhruvinishar 
Commit: 1d559d68bb599196dc6f7c5833488480587a045a

Modification: Improvement - Added formatting to the legend for the queen performance to include the names horizontally so that if many names are selected they are displayed without overlap
Source: Group Discussion
Team member: Dhruvi Nishar @dhruvinishar 
Commit: 08b22fc92eabca55918587cbc1fceb0ff480f64b
